In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
df = pd.read_excel('./tourist_files/kto_201901.xlsx',header = 1,usecols ='A:G', skipfooter = 4)
df

         국적      관광     상용    공용  유학/연수      기타       계
0      아시아주  765082  10837  1423  14087  125521  916950
1        일본  198805   2233   127    785    4576  206526
2        대만   86393     74    22    180    1285   87954
3        홍콩   34653     59     2     90    1092   35896
4       마카오    2506      2     0     17      45    2570
..      ...     ...    ...   ...    ...     ...     ...
62  아프리카 기타     768    718    90    206     908    2690
63     기타대륙      33      4     0      1      16      54
64     국적미상      33      4     0      1      16      54
65     교포소계       0      0     0      0   15526   15526
66       교포       0      0     0      0   15526   15526

[67 rows x 7 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   국적      67 non-null     object
 1   관광      67 non-null     int64
 2   상용      67 non-null     int64
 3   공용      67 non-null     int64
 4   유학/연수   67 non-null     int64
 5   기타      67 non-null     int64
 6   계       67 non-null     int64
dtypes: int64(6), object(1)
memory usage: 3.8+ KB

In [10]:
df['기준년월'] = '2019-01'
df

         국적      관광     상용    공용  유학/연수      기타       계     기준년월
0      아시아주  765082  10837  1423  14087  125521  916950  2019-01
1        일본  198805   2233   127    785    4576  206526  2019-01
2        대만   86393     74    22    180    1285   87954  2019-01
3        홍콩   34653     59     2     90    1092   35896  2019-01
4       마카오    2506      2     0     17      45    2570  2019-01
..      ...     ...    ...   ...    ...     ...     ...      ...
62  아프리카 기타     768    718    90    206     908    2690  2019-01
63     기타대륙      33      4     0      1      16      54  2019-01
64     국적미상      33      4     0      1      16      54  2019-01
65     교포소계       0      0     0      0   15526   15526  2019-01
66       교포       0      0     0      0   15526   15526  2019-01

[67 rows x 8 columns]

In [11]:
df.국적.unique()

array(['아시아주', '일본', '대만', '홍콩', '마카오', '태국', '말레이시아', '필리핀', '인도네시아',
       '싱가포르', '미얀마', '베트남', '인도', '스리랑카', '파키스탄', '방글라데시', '캄보디아', '몽골',
       '중국', '이란', '이스라엘', '터키', '우즈베키스탄', '카자흐스탄', 'GCC', '아시아 기타', '미주',
       '미국', '캐나다', '멕시코', '브라질', '미주 기타', '구주', '영국', '독일', '프랑스',
       '네덜란드', '스웨덴', '스위스', '이탈리아', '덴마크', '노르웨이', '벨기에', '오스트리아', '스페인',
       '그리스', '포르투갈', '핀란드', '아일랜드', '우크라이나', '러시아', '크로아티아', '루마니아',
       '불가리아', '폴란드', '구주 기타', '대양주', '오스트레일리아', '뉴질랜드', '대양주 기타',
       '아프리카주', '남아프리카공화국', '아프리카 기타', '기타대륙', '국적미상', '교포소계', '교포'],
      dtype=object)

In [39]:
continent_list = ['아시아주','아시아 기타','국적미상','미주','구주','대양주','아프리카주','아프리카 기타','기타대륙','교포소계','대양주 기타','구주 기타','미주 기타']

In [40]:
df=df[df.국적.isin(continent_list) == False]      # bool == False 하면 반대로 변경됨.
df.reset_index(drop = True, inplace = True)

In [41]:
df

          국적      관광    상용    공용  유학/연수     기타       계     기준년월
0         일본  198805  2233   127    785   4576  206526  2019-01
1         대만   86393    74    22    180   1285   87954  2019-01
2         홍콩   34653    59     2     90   1092   35896  2019-01
3        마카오    2506     2     0     17     45    2570  2019-01
4         태국   34004    37   199     96   6998   41334  2019-01
5      말레이시아   19043    95     7     99   2821   22065  2019-01
6        필리핀   14279   211   161    184  15638   30473  2019-01
7      인도네시아   14183   136    38    187   4298   18842  2019-01
8       싱가포르    8372    94     8     48   1333    9855  2019-01
9        미얀마    1304    10    31     67   3877    5289  2019-01
10       베트남   10739   763   110   1667   6904   20183  2019-01
11        인도    2318  2656    46    177   3474    8671  2019-01
12      스리랑카     157    54     5     28   1043    1287  2019-01
13      파키스탄     238   178    10    193    413    1032  2019-01
14     방글라데시     149   126    27     97    848    1247  2019-01
15      캄보디아     635    39    55     51   1915    2695  2019-01
16        몽골    8358    77   304    484    562    9785  2019-01
17        중국  320113  2993   138   8793  60777  392814  2019-01
18        이란      60    45    10     23     46     184  2019-01
19      이스라엘     727    12     0      9     57     805  2019-01
20        터키     792    13    32     36    912    1785  2019-01
21    우즈베키스탄    1958   561     0    407   2828    5754  2019-01
22     카자흐스탄    2185    24     7     92   1266    3574  2019-01
23       GCC    1550    37    14     72    103    1776  2019-01
24        미국   42989   418  2578    229  16523   62737  2019-01
25       캐나다    8034    57    30     43   4296   12460  2019-01
26       멕시코    1282    11     7     38    515    1853  2019-01
27       브라질    1136    16     9     41    403    1605  2019-01
28        영국    7982   175    17     41   1933   10148  2019-01
29        독일    4925   278    19    177   1451    6850  2019-01
30       프랑스    3773   297    48    288   1168    5574  2019-01
31      네덜란드    1592    47    16     77    537    2269  2019-01
32       스웨덴     844    29     6     18     85     982  2019-01
33       스위스     613    18     0     19     97     747  2019-01
34      이탈리아    1968    83    17     40    623    2731  2019-01
35       덴마크     520    21     6     16    188     751  2019-01
36      노르웨이     552    66     4     28    151     801  2019-01
37       벨기에     490    24     4     22    169     709  2019-01
38     오스트리아     544     8     2     13    209     776  2019-01
39       스페인    1010    36    15     52    255    1368  2019-01
40       그리스     481    17     4      0    273     775  2019-01
41      포르투갈     416    14     0     13    121     564  2019-01
42       핀란드     412    23     1     18    405     859  2019-01
43      아일랜드     392    15     1      2    185     595  2019-01
44     우크라이나     593    58     3     28   1580    2262  2019-01
45       러시아   17260   181    37    191   7525   25194  2019-01
46     크로아티아     226    12     0      3    250     491  2019-01
47      루마니아     412     8     4      3    445     872  2019-01
48      불가리아     154     1     1     10    265     431  2019-01
49       폴란드     713    10     0     27    574    1324  2019-01
50   오스트레일리아   12795    93    17     34   1346   14285  2019-01
51      뉴질랜드    2029    20    17      5    654    2725  2019-01
52  남아프리카공화국     368     9     1      6    616    1000  2019-01

In [42]:
contimnents = ['아시아']*25 + ['아프리카']*5 + ['유럽']*23 + ['오세아니아']*3+['아프리카']*2+['기타대륙']+['교포']

In [44]:
len(contimnents)

60

#####  2010~2019 년도 출입파일을 앞선 전처리한 후 하나의 df로 통합

In [56]:
import os

In [75]:
df_list = []
for i in os.listdir('./tourist_files')[:-1]:
    excel = './tourist_files'+i
    df = pd.read_excel('./tourist_files/kto_201901.xlsx',header = 1,usecols ='A:G', skipfooter = 4)
    df['기준년월'] = i.split('.xlsx')[0].split('_')[1]
    continent_list = ['아시아주','아시아 기타','국적미상','미주','구주','대양주','아프리카주','아프리카 기타','기타대륙','교포소계','대양주 기타','구주 기타','미주 기타']
    df=df[df.국적.isin(continent_list) == False]      # bool == False 하면 반대로 변경됨.
    df.reset_index(drop = True, inplace = True)
    
    df_list.append(df)
df_list

[          국적      관광    상용    공용  유학/연수     기타       계    기준년월
 0         일본  198805  2233   127    785   4576  206526  201001
 1         대만   86393    74    22    180   1285   87954  201001
 2         홍콩   34653    59     2     90   1092   35896  201001
 3        마카오    2506     2     0     17     45    2570  201001
 4         태국   34004    37   199     96   6998   41334  201001
 5      말레이시아   19043    95     7     99   2821   22065  201001
 6        필리핀   14279   211   161    184  15638   30473  201001
 7      인도네시아   14183   136    38    187   4298   18842  201001
 8       싱가포르    8372    94     8     48   1333    9855  201001
 9        미얀마    1304    10    31     67   3877    5289  201001
 10       베트남   10739   763   110   1667   6904   20183  201001
 11        인도    2318  2656    46    177   3474    8671  201001
 12      스리랑카     157    54     5     28   1043    1287  201001
 13      파키스탄     238   178    10    193    413    1032  201001
 14     방글라데시     149   126    27     97    848    1247  201001
 15      캄보디아     635    39    55     51   1915    2695  201001
 16        몽골    8358    77   304    484    562    9785  201001
 17        중국  320113  2993   138   8793  60777  392814  201001
 18        이란      60    45    10     23     46     184  201001
 19      이스라엘     727    12     0      9     57     805  201001
 20        터키     792    13    32     36    912    1785  201001
 21    우즈베키스탄    1958   561     0    407   2828    5754  201001
 22     카자흐스탄    2185    24     7     92   1266    3574  201001
 23       GCC    1550    37    14     72    103    1776  201001
 24        미국   42989   418  2578    229  16523   62737  201001
 25       캐나다    8034    57    30     43   4296   12460  201001
 26       멕시코    1282    11     7     38    515    1853  201001
 27       브라질    1136    16     9     41    403    1605  201001
 28        영국    7982   175    17     41   1933   10148  201001
 29        독일    4925   278    19    177   1451    6850  201001
 30       프랑스    3773   297    48    288   1168    5574  201001
 31      네덜란드    1592    47    16     77    537    2269  201001
 32       스웨덴     844    29     6     18     85     982  201001
 33       스위스     613    18     0     19     97     747  201001
 34      이탈리아    1968    83    17     40    623    2731  201001
 35       덴마크     520    21     6     16    188     751  201001
 36      노르웨이     552    66     4     28    151     801  201001
 37       벨기에     490    24     4     22    169     709  201001
 38     오스트리아     544     8     2     13    209     776  201001
 39       스페인    1010    36    15     52    255    1368  201001
 40       그리스     481    17     4      0    273     775  201001
 41      포르투갈     416    14     0     13    121     564  201001
 42       핀란드     412    23     1     18    405     859  201001
 43      아일랜드     392    15     1      2    185     595  201001
 44     우크라이나     593    58     3     28   1580    2262  201001
 45       러시아   17260   181    37    191   7525   25194  201001
 46     크로아티아     226    12     0      3    250     491  201001
 47      루마니아     412     8     4      3    445     872  201001
 48      불가리아     154     1     1     10    265     431  201001
 49       폴란드     713    10     0     27    574    1324  201001
 50   오스트레일리아   12795    93    17     34   1346   14285  201001
 51      뉴질랜드    2029    20    17      5    654    2725  201001
 52  남아프리카공화국     368     9     1      6    616    1000  201001
 53        교포       0     0     0      0  15526   15526  201001,
           국적      관광    상용    공용  유학/연수     기타       계    기준년월
 0         일본  198805  2233   127    785   4576  206526  201002
 1         대만   86393    74    22    180   1285   87954  201002
 2         홍콩   34653    59     2     90   1092   35896  201002
 3        마카오    2506     2     0     17     45    2570  201002
 4         태국   34004    37   199     96   6998   41334  201002
 5      말레이시아   19043    95     7     99   2821   22065  201002
 6        필리핀   14279   211   161    184  15638   30473  201002
 7      인도네시아   14183   136    38    187   4298   18842  201002
 8       싱가포르    8372    94     8     48   1333    9855  201002
 9        미얀마    1304    10    31     67   3877    5289  201002
 10       베트남   10739   763   110   1667   6904   20183  201002
 11        인도    2318  2656    46    177   3474    8671  201002
 12      스리랑카     157    54     5     28   1043    1287  201002
 13      파키스탄     238   178    10    193    413    1032  201002
 14     방글라데시     149   126    27     97    848    1247  201002
 15      캄보디아     635    39    55     51   1915    2695  201002
 16        몽골    8358    77   304    484    562    9785  201002
 17        중국  320113  2993   138   8793  60777  392814  201002
 18        이란      60    45    10     23     46     184  201002
 19      이스라엘     727    12     0      9     57     805  201002
 20        터키     792    13    32     36    912    1785  201002
 21    우즈베키스탄    1958   561     0    407   2828    5754  201002
 22     카자흐스탄    2185    24     7     92   1266    3574  201002
 23       GCC    1550    37    14     72    103    1776  201002
 24        미국   42989   418  2578    229  16523   62737  201002
 25       캐나다    8034    57    30     43   4296   12460  201002
 26       멕시코    1282    11     7     38    515    1853  201002
 27       브라질    1136    16     9     41    403    1605  201002
 28        영국    7982   175    17     41   1933   10148  201002
 29        독일    4925   278    19    177   1451    6850  201002
 30       프랑스    3773   297    48    288   1168    5574  201002
 31      네덜란드    1592    47    16     77    537    2269  201002
 32       스웨덴     844    29     6     18     85     982  201002
 33       스위스     613    18     0     19     97     747  201002
 34      이탈리아    1968    83    17     40    623    2731  201002
 35       덴마크     520    21     6     16    188     751  201002
 36      노르웨이     552    66     4     28    151     801  201002
 37       벨기에     490    24     4     22    169     709  201002
 38     오스트리아     544     8     2     13    209     776  201002
 39       스페인    1010    36    15     52    255    1368  201002
 40       그리스     481    17     4      0    273     775  201002
 41      포르투갈     416    14     0     13    121     564  201002
 42       핀란드     412    23     1     18    405     859  201002
 43      아일랜드     392    15     1      2    185     595  201002
 44     우크라이나     593    58     3     28   1580    2262  201002
 45       러시아   17260   181    37    191   7525   25194  201002
 46     크로아티아     226    12     0      3    250     491  201002
 47      루마니아     412     8     4      3    445     872  201002
 48      불가리아     154     1     1     10    265     431  201002
 49       폴란드     713    10     0     27    574    1324  201002
 50   오스트레일리아   12795    93    17     34   1346   14285  201002
 51      뉴질랜드    2029    20    17      5    654    2725  201002
 52  남아프리카공화국     368     9     1      6    616    1000  201002
 53        교포       0     0     0      0  15526   15526  201002,
           국적      관광    상용    공용  유학/연수     기타       계    기준년월
 0         일본  198805  2233   127    785   4576  206526  201003
 1         대만   86393    74    22    180   1285   87954  201003
 2         홍콩   34653    59     2     90   1092   35896  201003
 3        마카오    2506     2     0     17     45    2570  201003
 4         태국   34004    37   199     96   6998   41334  201003
 5      말레이시아   19043    95     7     99   2821   22065  201003
 6        필리핀   14279   211   161    184  15638   30473  201003
 7      인도네시아   14183   136    38    187   4298   18842  201003
 8       싱가포르    8372    94     8     48   1333    9855  201003
 9        미얀마    1304    10    31     67   3877    5289  201003
 10       베트남   10739   763   110   1667   6904   20183  201003
 11        인도    2318  2656    46    177   3474    8671  201003
 12      스리랑카     157    54     5     28   1043    1287  201003
 13      파키스탄     238   178    10    193    413    1032  201003
 14     방글라데시     149   126    27     97    848    1247  201003
 15      캄보디아     635    39    55     51   1915    2695  201003
 16        몽골    8358    77   304    484    562    9785  201003
 17        중국  320113  2993   138   8793  60777  392814  201003
 18        이란      60    45    10     23     46     184  201003
 19      이스라엘     727    12     0      9     57     805  201003
 20        터키     792    13    32     36    912    1785  201003
 21    우즈베키스탄    1958   561     0    407   2828    5754  201003
 22     카자흐스탄    2185    24     7     92   1266    3574  201003
 23       GCC    1550    37    14     72    103    1776  201003
 24        미국   42989   418  2578    229  16523   62737  201003
 25       캐나다    8034    57    30     43   4296   12460  201003
 26       멕시코    1282    11     7     38    515    1853  201003
 27       브라질    1136    16     9     41    403    1605  201003
 28        영국    7982   175    17     41   1933   10148  201003
 29        독일    4925   278    19    177   1451    6850  201003
 30       프랑스    3773   297    48    288   1168    5574  201003
 31      네덜란드    1592    47    16     77    537    2269  201003
 32       스웨덴     844    29     6     18     85     982  201003
 33       스위스     613    18     0     19     97     747  201003
 34      이탈리아    1968    83    17     40    623    2731  201003
 35       덴마크     520    21     6     16    188     751  201003
 36      노르웨이     552    66     4     28    151     801  201003
 37       벨기에     490    24     4     22    169     709  201003
 38     오스트리아     544     8     2     13    209     776  201003
 39       스페인    1010    36    15     52    255    1368  201003
 40       그리스     481    17     4      0    273     775  201003
 41      포르투갈     416    14     0     13    121     564  201003
 42       핀란드     412    23     1     18    405     859  201003
 43      아일랜드     392    15     1      2    185     595  201003
 44     우크라이나     593    58     3     28   1580    2262  201003
 45       러시아   17260   181    37    191   7525   25194  201003
 46     크로아티아     226    12     0      3    250     491  201003
 47      루마니아     412     8     4      3    445     872  201003
 48      불가리아     154     1     1     10    265     431  201003
 49       폴란드     713    10     0     27    574    1324  201003
 50   오스트레일리아   12795    93    17     34   1346   14285  201003
 51      뉴질랜드    2029    20    17      5    654    2725  201003
 52  남아프리카공화국     368     9     1      6    616    1000  201003
 53        교포       0     0     0      0  15526   15526  201003,
           국적      관광    상용    공용  유학/연수     기타       계    기준년월
 0         일본  198805  2233   127    785   4576  206526  201004
 1         대만   86393    74    22    180   1285   87954  201004
 2         홍콩   34653    59     2     90   1092   35896  201004
 3        마카오    2506     2     0     17     45    2570  201004
 4         태국   34004    37   199     96   6998   41334  201004
 5      말레이시아   19043    95     7     99   2821   22065  201004
 6        필리핀   14279   211   161    184  15638   30473  201004
 7      인도네시아   14183   136    38    187   4298   18842  201004
 8       싱가포르    8372    94     8     48   1333    9855  201004
 9        미얀마    1304    10    31     67   3877    5289  201004
 10       베트남   10739   763   110   1667   6904   20183  201004
 11        인도    2318  2656    46    177   3474    8671  201004
 12      스리랑카     157    54     5     28   1043    1287  201004
 13      파키스탄     238   178    10    193    413    1032  201004
 14     방글라데시     149   126    27     97    848    1247  201004
 15      캄보디아     635    39    55     51   1915    2695  201004
 16        몽골    8358    77   304    484    562    9785  201004
 17        중국  320113  2993   138   8793  60777  392814  201004
 18        이란      60    45    10     23     46     184  201004
 19      이스라엘     727    12     0      9     57     805  201004
 20        터키     792    13    32     36    912    1785  201004
 21    우즈베키스탄    1958   561     0    407   2828    5754  201004
 22     카자흐스탄    2185    24     7     92   1266    3574  201004
 23       GCC    1550    37    14     72    103    1776  201004
 24        미국   42989   418  2578    229  16523   62737  201004
 25       캐나다    8034    57    30     43   4296   12460  201004
 26       멕시코    1282    11     7     38    515    1853  201004
 27       브라질    1136    16     9     41    403    1605  201004
 28        영국    7982   175    17     41   1933   10148  201004
 29        독일    4925   278    19    177   1451    6850  201004
 30       프랑스    3773   297    48    288   1168    5574  201004
 31      네덜란드    1592    47    16     77    537    2269  201004
 32       스웨덴     844    29     6     18     85     982  201004
 33       스위스     613    18     0     19     97     747  201004
 34      이탈리아    1968    83    17     40    623    2731  201004
 35       덴마크     520    21     6     16    188     751  201004
 36      노르웨이     552    66     4     28    151     801  201004
 37       벨기에     490    24     4     22    169     709  201004
 38     오스트리아     544     8     2     13    209     776  201004
 39       스페인    1010    36    15     52    255    1368  201004
 40       그리스     481    17     4      0    273     775  201004
 41      포르투갈     416    14     0     13    121     564  201004
 42       핀란드     412    23     1     18    405     859  201004
 43      아일랜드     392    15     1      2    185     595  201004
 44     우크라이나     593    58     3     28   1580    2262  201004
 45       러시아   17260   181    37    191   7525   25194  201004
 46     크로아티아     226    12     0      3    250     491  201004
 47      루마니아     412     8     4      3    445     872  201004
 48      불가리아     154     1     1     10    265     431  201004
 49       폴란드     713    10     0     27    574    1324  201004
 50   오스트레일리아   12795    93    17     34   1346   14285  201004
 51      뉴질랜드    2029    20    17      5    654    2725  201004
 52  남아프리카공화국     368     9     1      6    616    1000  201004
 53        교포       0     0     0      0  15526   15526  201004,
           국적      관광    상용    공용  유학/연수     기타       계    기준년월
 0         일본  198805  2233   127    785   4576  206526  201005
 1         대만   86393    74    22    180   1285   87954  201005
 2         홍콩   34653    59     2     90   1092   35896  201005
 3        마카오    2506     2     0     17     45    2570  201005
 4         태국   34004    37   199     96   6998   41334  201005
 5      말레이시아   19043    95     7     99   2821   22065  201005
 6        필리핀   14279   211   161    184  15638   30473  201005
 7      인도네시아   14183   136    38    187   4298   18842  201005
 8       싱가포르    8372    94     8     48   1333    9855  201005
 9        미얀마    1304    10    31     67   3877    5289  201005
 10       베트남   10739   763   110   1667   6904   20183  201005
 11        인도    2318  2656    46    177   3474    8671  201005
 12      스리랑카     157    54     5     28   1043    1287  201005
 13      파키스탄     238   178    10    193    413    1032  201005
 14     방글라데시     149   126    27     97    848    1247  201005
 15      캄보디아     635    39    55     51   1915    2695  201005
 16        몽골    8358    77   304    484    562    9785  201005
 17        중국  320113  2993   138   8793  60777  392814  201005
 18        이란      60    45    10     23     46     184  201005
 19      이스라엘     727    12     0      9     57     805  201005
 20        터키     792    13    32     36    912    1785  201005
 21    우즈베키스탄    1958   561     0    407   2828    5754  201005
 22     카자흐스탄    2185    24     7     92   1266    3574  201005
 23       GCC    1550    37    14     72    103    1776  201005
 24        미국   42989   418  2578    229  16523   62737  201005
 25       캐나다    8034    57    30     43   4296   12460  201005
 26       멕시코    1282    11     7     38    515    1853  201005
 27       브라질    1136    16     9     41    403    1605  201005
 28        영국    7982   175    17     41   1933   10148  201005
 29        독일    4925   278    19    177   1451    6850  201005
 30       프랑스    3773   297    48    288   1168    5574  201005
 31      네덜란드    1592    47    16     77    537    2269  201005
 32       스웨덴     844    29     6     18     85     982  201005
 33       스위스     613    18     0     19     97     747  201005
 34      이탈리아    1968    83    17     40    623    2731  201005
 35       덴마크     520    21     6     16    188     751  201005
 36      노르웨이     552    66     4     28    151     801  201005
 37       벨기에     490    24     4     22    169     709  201005
 38     오스트리아     544     8     2     13    209     776  201005
 39       스페인    1010    36    15     52    255    1368  201005
 40       그리스     481    17     4      0    273     775  201005
 41      포르투갈     416    14     0     13    121     564  201005
 42       핀란드     412    23     1     18    405     859  201005
 43      아일랜드     392    15     1      2    185     595  201005
 44     우크라이나     593    58     3     28   1580    2262  201005
 45       러시아   17260   181    37    191   7525   25194  201005
 46     크로아티아     226    12     0      3    250     491  201005
 47      루마니아     412     8     4      3    445     872  201005
 48      불가리아     154     1     1     10    265     431  201005
 49       폴란드     713    10     0     27    574    1324  201005
 50   오스트레일리아   12795    93    17     34   1346   14285  201005
 51      뉴질랜드    2029    20    17      5    654    2725  201005
 52  남아프리카공화국     368     9     1      6    616    1000  201005
 53        교포       0     0     0      0  15526   15526  201005,
           국적      관광    상용    공용  유학/연수     기타       계    기준년월
 0         일본  198805  2233   127    785   4576  206526  201006
 1         대만   86393    74    22    180   1285   87954  201006
 2         홍콩   34653    59     2     90   1092   35896  201006
 3        마카오    2506     2     0     17     45    2570  201006
 4         태국   34004    37   199     96   6998   41334  201006
 5      말레이시아   19043    95     7     99   2821   22065  201006
 6        필리핀   14279   211   161    184  15638   30473  201006
 7      인도네시아   14183   136    38    187   4298   18842  201006
 8       싱가포르    8372    94     8     48   1333    9855  201006
 9        미얀마    1304    10    31     67   3877    5289  201006
 10       베트남   10739   763   110   1667   6904   20183  201006
 11        인도    2318  2656    46    177   3474    8671  201006
 12      스리랑카     157    54     5     28   1043    1287  201006
 13      파키스탄     238   178    10    193    413    1032  201006
 14     방글라데시     149   126    27     97    848    1247  201006
 15      캄보디아     635    39    55     51   1915    2695  201006
 16        몽골    8358    77   304    484    562    9785  201006
 17        중국  320113  2993   138   8793  60777  392814  201006
 18        이란      60    45    10     23     46     184  201006
 19      이스라엘     727    12     0      9     57     805  201006
 20        터키     792    13    32     36    912    1785  201006
 21    우즈베키스탄    1958   561     0    407   2828    5754  201006
 22     카자흐스탄    2185    24     7     92   1266    3574  201006
 23       GCC    1550    37    14     72    103    1776  201006
 24        미국   42989   418  2578    229  16523   62737  201006
 25       캐나다    8034    57    30     43   4296   12460  201006
 26       멕시코    1282    11     7     38    515    1853  201006
 27       브라질    1136    16     9     41    403    1605  201006
 28        영국    7982   175    17     41   1933   10148  201006
 29        독일    4925   278    19    177   1451    6850  201006
 30       프랑스    3773   297    48    288   1168    5574  201006
 31      네덜란드    1592    47    16     77    537    2269  201006
 32       스웨덴     844    29     6     18     85     982  201006
 33       스위스     613    18     0     19     97     747  201006
 34      이탈리아    1968    83    17     40    623    2731  201006
 35       덴마크     520    21     6     16    188     751  201006

In [99]:
pd.concat(df_list)

          국적      관광    상용   공용  유학/연수     기타       계    기준년월
0         일본  198805  2233  127    785   4576  206526  201001
1         대만   86393    74   22    180   1285   87954  201001
2         홍콩   34653    59    2     90   1092   35896  201001
3        마카오    2506     2    0     17     45    2570  201001
4         태국   34004    37  199     96   6998   41334  201001
..       ...     ...   ...  ...    ...    ...     ...     ...
49       폴란드     713    10    0     27    574    1324  201908
50   오스트레일리아   12795    93   17     34   1346   14285  201908
51      뉴질랜드    2029    20   17      5    654    2725  201908
52  남아프리카공화국     368     9    1      6    616    1000  201908
53        교포       0     0    0      0  15526   15526  201908

[6264 rows x 8 columns]

In [93]:
df = df_list[0]
for i in df_list[1:] :
    df = pd.concat([df,i])
df

          국적      관광    상용   공용  유학/연수     기타       계    기준년월
0         일본  198805  2233  127    785   4576  206526  201001
1         대만   86393    74   22    180   1285   87954  201001
2         홍콩   34653    59    2     90   1092   35896  201001
3        마카오    2506     2    0     17     45    2570  201001
4         태국   34004    37  199     96   6998   41334  201001
..       ...     ...   ...  ...    ...    ...     ...     ...
49       폴란드     713    10    0     27    574    1324  201908
50   오스트레일리아   12795    93   17     34   1346   14285  201908
51      뉴질랜드    2029    20   17      5    654    2725  201908
52  남아프리카공화국     368     9    1      6    616    1000  201908
53        교포       0     0    0      0  15526   15526  201908

[6264 rows x 8 columns]

In [94]:
df.reset_index()

      index        국적      관광    상용   공용  유학/연수     기타       계    기준년월
0         0        일본  198805  2233  127    785   4576  206526  201001
1         1        대만   86393    74   22    180   1285   87954  201001
2         2        홍콩   34653    59    2     90   1092   35896  201001
3         3       마카오    2506     2    0     17     45    2570  201001
4         4        태국   34004    37  199     96   6998   41334  201001
...     ...       ...     ...   ...  ...    ...    ...     ...     ...
6259     49       폴란드     713    10    0     27    574    1324  201908
6260     50   오스트레일리아   12795    93   17     34   1346   14285  201908
6261     51      뉴질랜드    2029    20   17      5    654    2725  201908
6262     52  남아프리카공화국     368     9    1      6    616    1000  201908
6263     53        교포       0     0    0      0  15526   15526  201908

[6264 rows x 9 columns]